language: python

git:
  depth: false

python:
  - "3.6"

before_install:
  # A mujoco key has to be added on travis CI as
  # an environment variable.
  - mkdir -p $HOME/.mujoco
  - touch $HOME/.mujoco/mjkey.txt
  - echo -e $MJKEY > $HOME/.mujoco/mjkey.txt
  - echo | sudo add-apt-repository ppa:xorg-edgers/ppa
  - sudo apt update
  - sudo apt install wget libosmesa6-dev libglew-dev patchelf
  - pip install --upgrade pip
  - wget https://www.roboti.us/download/mujoco200_linux.zip -O mujoco.zip
  - unzip mujoco.zip -d $HOME/.mujoco
  - mv $HOME/.mujoco/mujoco200_linux $HOME/.mujoco/mujoco200
  - rm mujoco.zip
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/travis/.mujoco/mujoco200/bin
  # Setup dummy X server display. Putting these at the beginning
  # gives time for X to come up while waiting for pipenv installation.
  - DEBIAN_FRONTEND=noninteractive sudo apt install -y xvfb pulseaudio
  - display_num=100
  - export DISPLAY=:"${display_num}"
  - Xvfb "${DISPLAY}" -screen 0 1024x768x24 & pulseaudio -D --exit-idle-time=-1

install:
  - pip install pipenv
  - pipenv install

script:
  - pipenv run pytest -v
